### ISSUE TITLE
GCC15 tracker

### ISSUE THREAD

**Issue by SchrodingerZhu** [Lancern/mlir-gccjit#42]
Tracking compatibility with upcoming GCC 15 release.

Known issues:

- [ ] [[15 Regression] GIMPLE pass asan0 no longer works after r15-5528](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117886)
- [ ] [[15 Regression] gcc_jit_block_add_assignment_op GCC_JIT_BINARY_OP_BITWISE_XOR rejects vector types](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117903)

Planned new features:

- [ ] target builtin
- [ ] unnamed tmp variable
